<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Maple.Result</AssemblyName>
    <RootNamespace>Maple.Result</RootNamespace>

    <PackageId>Maple.Result</PackageId>
    <Title>Maple.Result — Result pattern with RFC 9457 errors</Title>
    <Description>An abstraction which contains the value or the error of the operation. It can be mapped to the HTTP response if needed.</Description>
    <Authors>Tom Maple</Authors>
    <PublisherName>Tom Maple</PublisherName>
    <PackageIcon>icon.png</PackageIcon>
    <PackageTags>Result;Error;RFC-9457;RFC-7807</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>

    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>

    <PackageProjectUrl>https://github.com/TomMaple/Result</PackageProjectUrl>
    <RepositoryUrl>https://github.com/TomMaple/Result</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(GITHUB_ACTIONS)' == 'true'">
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
  </PropertyGroup>

  <PropertyGroup>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Maple.Result.Tests.Unit" />
    <InternalsVisibleTo Include="Maple.Result.Extensions.HttpClient" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\.resources\icon.png" Pack="true" PackagePath="" />
    <None Include="..\..\LICENSE" Pack="true" PackagePath="" />
    <None Include="..\..\README.md" Pack="true" PackagePath="" />
  </ItemGroup>

</Project>
